### ISSUE TITLE
BaseXmlSyncState Cursor not closed

### ISSUE THREAD

**Issue by cklar** [dmfs/android-syncstate#1]
The Cursor which is opened in the BaseXmlSyncState is not closed. 

`2018-08-14 08:16:37.480 26972-26981/com.mail.mobile.android.mail.debug:contactssync E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:223)
        at android.content.ContentResolver$CursorWrapperInner.<init>(ContentResolver.java:2925)
        at android.content.ContentResolver.query(ContentResolver.java:780)
        at android.content.ContentResolver.query(ContentResolver.java:704)
        at android.content.ContentResolver.query(ContentResolver.java:662)
        at org.dmfs.android.syncstate.BaseXmlSyncState.load(Unknown Source:26)
        at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:321)`

**Comment by dmfs** [comment]
Ouch! Will fix that.
